### ISSUE TITLE
onTag event fires twice.

### ISSUE THREAD

**Issue by mazenhalawi** [eyoeldefare/textfield_tags#52]
Im not sure why this is happening, when i add a tag, the event onTag fires twice in quick successions. 

Usually what i do is i check if the tag already exist in the tag, if it does i display an alert that the tag is already in the list. I need to do that even though the widget doesnt add duplicates but since it doesnt support multiline so the user can forget what he added and not know why its not taking it. 

so now what happens with the double fire of the event onTag. in the first event it saves it to the list, since its a new tag, in the second event it checks that the tag is already in the list and fires the alert saying that the tag already exist.

**Comment by eyoeldefare** [comment]
Thank you for letting me know, I will see to it seen.

**Comment by eyoeldefare** [comment]
`onTag` sends all entered values to the developer. This is why we made the `validator` functionality so the developer can customize his/her own solution not dictated by us. 

For example, in your case, you can use `Set` collection instead of `List` to insure no duplicated are entered and display a warning using the validator or your own alert if you choose.
